
console.log("Starting debug...");
import './config/db.js';
console.log("db loaded");
import './config/firebase.js';
console.log("firebase loaded");
import './config/s3.js';
console.log("s3 loaded");
import './models/User.js';
console.log("User model loaded");
import './models/Chat.js';
console.log("Chat model loaded");
import './models/Group.js';
console.log("Group model loaded");
import './models/Note.js';
console.log("Note model loaded");
import './middleware/authMiddleware.js';
console.log("authMiddleware loaded");
import './middleware/upload.js';
console.log("upload middleware loaded");
import './controllers/chatController.js';
console.log("chatController loaded");
import './controllers/groupController.js';
console.log("groupController loaded");
import './controllers/noteController.js';
console.log("noteController loaded");
import './controllers/uploadController.js';
console.log("uploadController loaded");
import './routes/noteRoutes.js';
console.log("noteRoutes loaded");
import './routes/groupRoutes.js';
console.log("groupRoutes loaded");
import './routes/uploadRoutes.js';
console.log("uploadRoutes loaded");
import './routes/userRoutes.js';
console.log("userRoutes loaded");
import './routes/aiRoutes.js';
console.log("aiRoutes loaded");

console.log("ALL LOADED");
